version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: .
      target: dev
    restart: always
    command: npm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/.next
      - /app/node_modules
    ports:
      - 3000:3000
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: example123
      POSTGRES_USER: edimario
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
